### ISSUE TITLE
"prl.readrnx" can't return values

### ISSUE THREAD

**Issue by wanglei072508** [ebhrz/TDL-GNSS#1]
I installed pyrtklib through "pip",and I tried the "python hybrid_network_train.py config/hybrid_share/klt3_train.json". It seems like that the fuction "prl.readrnx" don't return values of "obs'. 
Is there more steps I should do before I run " hybrid_network_train.py"
os is Windows.

**Comment by ebhrz** [comment]
Hi @wanglei072508 , ***readrnx*** will not directly return a value. ***obs***, ***eph***, and ***sta*** are returned by the pointer. If there is no data in the pass-in variable (e.g. ***obs***), I think you can check is path of the data file correct. Do you download the dataset from the link and put into the ***data*** folder? Maybe you can show me your folder structure. Besides, you can set the log file to see what happened in the process
```python
prl.traceopen("rtk.log")
prl.tracelevel(4)
```
Then you can check "rtk.log" to see if the path correct and the data is not missing.

**Comment by wanglei072508** [comment]
THANKS. YES，I have downloaded the dataset. And this is my  folder structure and rtk.log .
![Snipaste_2024-10-10_16-44-15](https://github.com/user-attachments/assets/ac3a63ee-05ae-4491-b729-0795e2de576f)
![Snipaste_2024-10-10_16-44-39](https://github.com/user-attachments/assets/fd2c3884-39d3-4fb8-b963-48d6765cd2e8)

**Comment by ebhrz** [comment]
Hi @wanglei072508 , I reproduced your issue and it's caused by the different system path separator. You can change the "/" to "\\" in the path in the config file.

```json
"obs":["data\\0610_KLT\\GEOP161D.21o"],
"eph":"data\\0610_KLT\\sta\\hksc161d.21*",
```
