### ISSUE TITLE
ValueError when running weight_network_train.py

### ISSUE THREAD

**Issue by lifang63** [ebhrz/TDL-GNSS#2]
Dear Developer,

I'm encountering an error when running the weight_network_train.py script. Here’s the output I receive:

D:\Software\Anaconda\install\python.exe D:/Projects/TDL-GNSS/weight_network_train.py
Loaded config: {'obs': ['data/0610_KLT/COM38_210610_025603.obs'], 'eph': 'data/0610_KLT/sta/hksc161d.21*', 'gt': 'data/0610_KLT/20210610_100.txt', 'start_time': 1623297151, 'end_time': 1623297556, 'model': 'model/weight', 'mode': 'train', 'epoch': 500}
obs: <pyrtklib.Release.pyrtklib.obs_t object at 0x0000020AABDB0870>
Gathered data: []
Number of arrays: 0
Traceback (most recent call last):
  File "D:/Projects/TDL-GNSS/weight_network_train.py", line 86, in <module>
    norm_data = np.vstack(gather_data)
  File "<__array_function__ internals>", line 200, in vstack
  File "D:\Software\Anaconda\install\lib\site-packages\numpy\core\shape_base.py", line 296, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate

**Background**:

- I have downloaded the required dataset and extracted its contents into a folder named data.
- The configuration file loaded as follows:
{'obs': ['data/0610_KLT/COM38_210610_025603.obs'], 'eph': 'data/0610_KLT/sta/hksc161d.21*', 'gt': 'data/0610_KLT/20210610_100.txt', 'start_time': 1623297151, 'end_time': 1623297556, 'model': 'model/weight', 'mode': 'train', 'epoch': 500}

**Question**:

Could you please help me understand why I am encountering the ValueError: need at least one array to concatenate? What steps should I take to resolve this issue?

Thank you for your assistance!

**Comment by ebhrz** [comment]
Hi @lifang63 , the last issue also mentioned the problem. It's because you use Windows and the system path separator is different. Change '/' to '\\' in the config file:
```json
    "obs":["data\\0610_KLT\\GEOP161D.21o"],
    "eph":"data\\0610_KLT\\sta\\hksc161d.21*",
```
BTW, have you resolved the "module not found" problem in pyrtklib?

**Comment by lifang63** [comment]
> Hi @lifang63 , the last issue also mentioned the problem. #1 It's because you use Windows and the system path separator is different. Change '/' to '\' in the config file:
> 
> ```json
>     "obs":["data\\0610_KLT\\GEOP161D.21o"],
>     "eph":"data\\0610_KLT\\sta\\hksc161d.21*",
> ```
> 
> BTW, have you resolved the "module not found" problem in pyrtklib?

Thank you for the suggestion. I've updated the config file as you mentioned, and the issue is resolved. Also, I’ve fixed the ‘module not found’ problem in pyrtklib. I appreciate your help.
