### ISSUE TITLE
 a few requests and questions

### ISSUE THREAD

**Issue by GarlanLou** [ebhrz/TDL-GNSS#3]
Great job! I have a few requests and questions as follows:
1. Could you specify the Python version used, as well as the versions of each package?
2. I couldn't find the challenging dataset GEOP161D.21o in the data collection. Could you provide it?
Looking forward to your response.

**Comment by ebhrz** [comment]
Hi Garlan
1. I use Python3.8 as the main version, but it should work well on below versions as mentioned in [pyrtklib](https://github.com/IPNL-POLYU/pyrtklib#20240710-add-windows-support)
![4020050188](https://github.com/user-attachments/assets/34584235-ed48-49a6-8694-40d687adc0a7)
2. This file is in the earlier dropbox link at https://www.dropbox.com/scl/fi/d3urwaquf5ema5j0unmt4/data.zip?rlkey=tuwpx9pdzqtdvoeoqwhcc5gi8&st=wh5qhg6e&dl=0

**Comment by ebhrz** [comment]
For the dependencies, I use pytorch 2.1.2, and pyrtklib 0.2.7. I think version of the rest dependencies such as numpy/pandas are not compulsory, any version is OK.

**Comment by GarlanLou** [comment]
Thank you very much for your answer. Again, great respect for your work.
